---
title: "Título do dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
    favicon: favicon.png
params:
  uf: "BA"
  ano_idh: "1991"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dados)
library(magrittr)
library(ggplot2)
```


Aba 1
===========

Essa aba vai ter duas linhas!

### Primeira linha

```{r}
pinguins %>% 
  dplyr::count(especie) %>% 
  ggplot(aes(x = especie, y = n,fill = especie)) + 
  geom_col() +
  ggthemes::theme_fivethirtyeight()
```

### Segunda linha

```{r}
pinguins %>% 
  dplyr::count(especie) %>% 
  dplyr::mutate(especie = forcats::fct_reorder(especie, n)) %>% 
  ggplot(aes(x = especie, y = n,fill = especie)) + 
  geom_col() 
```


Aba 2
===========

Essa aba vai ter colunas!

Column {data-width=650}
-----------------------------------------------------------------------

### Gráfico

```{r}
library(sf)
municipios <- readr::read_rds("../dados/geobr/municipios_todos.rds")
p <- abjData::pnud_min %>%
  dplyr::filter(uf_sigla == params$uf, ano == params$ano_idh) %>% 
  dplyr::mutate(code_muni = as.numeric(muni_id)) %>% 
  dplyr::inner_join(municipios, "code_muni") %>% 
  sf::st_as_sf() %>% 
  ggplot() +
  geom_sf(aes(fill = idhm), colour = "black", size = .2) +
  scale_fill_viridis_c(begin = .2, end = .8, option = "A") +
  theme_void()

## pesado!
# plotly::ggplotly(p)
p
```

Column {data-width=350}
-----------------------------------------------------------------------

### Tabela

```{r}
abjData::pnud_min %>% 
  dplyr::filter(uf_sigla == params$uf, ano == params$ano_idh) %>% 
  dplyr::select(ano, muni_nm, dplyr::starts_with("idhm")) %>% 
  DT::datatable(options = list(pageLength = 20))
```

### Tabela 2 na mesma coluna

```{r}
abjData::pnud_min %>% 
  dplyr::filter(uf_sigla == params$uf) %>% 
  dplyr::select(muni_nm, dplyr::starts_with("idhm")) %>% 
  DT::datatable(options = list(pageLength = 20))
```

