
```{r, include=FALSE}
`%>%` <- magrittr::`%>%`
blue <- function(x) {
  glue::glue(
    '<span style="color:#6495ed; font-weight: bold;">{x}</span>'
  ) %>% 
    htmltools::HTML()
}

options(width = 85)
```

```{r include=FALSE}
# install.packages("devtools")
# devtools::install_github("gadenbuie/xaringanExtra")
```

```{r include=FALSE}
library(magrittr, include.only = "%>%")
```

```{r xaringanExtra-clipboard, echo=FALSE}
xaringanExtra::use_clipboard()
```

```{r xaringanExtra-search, echo=FALSE}
#xaringanExtra::use_search(show_icon = TRUE, position = "top-left")
```

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```


```{r xaringan-scribble, echo=FALSE}
#xaringanExtra::use_scribble()
```

```{r xaringan-extra-styles, include=FALSE}
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = FALSE  #<<
)
```

```{r xaringan-fit-screen, echo=FALSE}
#xaringanExtra::use_fit_screen()
```

```{r xaringan-panelset, echo=FALSE}
xaringanExtra::use_panelset()
```